name: Déployer vers GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Téléverser l'artéfact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Déploiement
        id: deployment
        uses: actions/deploy-pages@v4